name: Install test

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:

jobs:
  test-platforms:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [windows-latest, windows-2019, ubuntu-latest, ubuntu-16.04, macos-latest]
        php-versions: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: zlib, mbstring, simplexml, json, dom, openssl, zip

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

# Needs crossplatform fix. #
#      - name: Setup Composer Token
#        if: secrets.COMPOSER_TOKEN != ''
#        run: composer config github-oauth.github.com "${{ secrets.COMPOSER_TOKEN }}"

      - name: Install packages
        run: composer install --prefer-dist

      - name: Install Phalcon
        if: runner.os != 'windows'
        run: sudo bin/pickle install phalcon

      - name: Install Phalcon
        if: runner.os == 'windows'
        run: bin/pickle install phalcon

      - name: Verify install phalcon
        run: php --ri phalcon
